"""Distributional fidelity metrics.

Three complementary views, because any single one is easy to pass by accident:

* **Kolmogorov-Smirnov** per marginal - catches the wrong shape in any one variable.
* **Correlation delta** - catches marginals that are individually right but jointly wrong,
  which is the classic failure of independently-sampled synthetic data.
* **Benford conformance** - catches amounts that were generated by rounding or by a process
  with the wrong multiplicative structure. Real transaction amounts follow Benford closely;
  naively generated ones usually do not.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
from scipy import stats

CONTINUOUS = ["log_amount", "amount_z"]
DISCRETE = ["hour", "day_of_week"]


@dataclass(slots=True)
class KSResult:
    column: str
    statistic: float
    p_value: float

    @property
    def verdict(self) -> str:
        """KS statistic bands. These are conventions, not thresholds with theoretical force.

        With hundreds of thousands of rows the p-value is essentially always significant, so
        the *effect size* is what carries information - which is why the statistic is reported
        rather than a pass/fail on p.
        """
        if self.statistic < 0.05:
            return "excellent"
        if self.statistic < 0.10:
            return "good"
        if self.statistic < 0.20:
            return "fair"
        return "poor"


def ks_table(
    synthetic: pd.DataFrame, reference: pd.DataFrame, columns: list[str] | None = None
) -> list[KSResult]:
    """Two-sample KS statistic per comparable marginal."""
    out = []
    for col in columns or (CONTINUOUS + DISCRETE):
        if col not in synthetic or col not in reference:
            continue
        s = synthetic[col].to_numpy(dtype=float)
        r = reference[col].to_numpy(dtype=float)
        stat, p = stats.ks_2samp(s, r)
        out.append(KSResult(col, float(stat), float(p)))
    return out


def correlation_delta(
    synthetic: pd.DataFrame, reference: pd.DataFrame, columns: list[str] | None = None
) -> float:
    """Frobenius norm of the difference between correlation matrices, normalised.

    Zero means the joint linear structure matches. This is the metric that catches a generator
    which gets every marginal right by sampling each column independently.
    """
    cols = [c for c in (columns or CONTINUOUS + DISCRETE) if c in synthetic and c in reference]
    a = synthetic[cols].corr().to_numpy()
    b = reference[cols].corr().to_numpy()
    delta = np.nan_to_num(a - b)
    return float(np.linalg.norm(delta) / np.sqrt(delta.size))


def benford_conformance(amounts: np.ndarray) -> dict:
    """Compare leading-digit frequencies against Benford's law.

    Reported as mean absolute deviation across the nine digits. Under 0.006 is conventionally
    "close conformity" in the forensic-accounting literature; above 0.015 is "nonconformity".
    """
    a = np.abs(amounts[amounts > 0])
    leading = (a / (10 ** np.floor(np.log10(a)))).astype(int)
    observed = np.array([(leading == d).mean() for d in range(1, 10)])
    expected = np.log10(1 + 1 / np.arange(1, 10))
    mad = float(np.abs(observed - expected).mean())
    return {
        "observed": observed.tolist(),
        "expected": expected.tolist(),
        "mad": mad,
        "verdict": "close" if mad < 0.006 else "acceptable" if mad < 0.015 else "nonconforming",
    }


def summarise(synthetic: pd.DataFrame, reference: pd.DataFrame, name: str) -> dict:
    """Full distributional summary, scoped to the columns this reference can evidence."""
    from janus.generate.fidelity.align import COMPARABLE_COLUMNS

    columns = COMPARABLE_COLUMNS.get(name)
    ks = ks_table(synthetic, reference, columns)
    return {
        "reference": name,
        "compared_on": columns,
        "n_synthetic": len(synthetic),
        "n_reference": len(reference),
        "ks": [{"column": k.column, "statistic": round(k.statistic, 4),
                "p_value": k.p_value, "verdict": k.verdict} for k in ks],
        "ks_mean": round(float(np.mean([k.statistic for k in ks])), 4) if ks else None,
        "correlation_delta": round(correlation_delta(synthetic, reference, columns), 4),
        "benford_synthetic": benford_conformance(synthetic.amount.to_numpy()),
        "benford_reference": benford_conformance(reference.amount.to_numpy()),
    }
